project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - styles.css

website:
  title: "Qing Chang"
  page-navigation: true
  page-footer:  
    left: >-
     &#169; 2026 Qing Chang &#8729; Made with [Quarto](https://quarto.org).
    center: >-
     [License](/license.html)
  navbar:
    pinned: true
    left:
      - text: Home
        icon: house
        href: index.qmd

      - text: Research
        icon: journal-text
        href: articles.qmd

      - text: Projects
        icon: terminal
        href: projects.qmd

      - text: Teaching
        icon: mortarboard
        href: teaching.qmd

      - text: CV
        icon: file-earmark-person
        href: Qing_Chang_CV.pdf

      - text: Contact
        icon: envelope
        href: contact.qmd
    
    right:
      - icon: github
        aria-label: GitHub
        href: https://github.com/QingChang166

      - icon: bi-twitter-x
        aria-label: X
        href: https://x.com/QingChang19

      - icon: envelope
        aria-label: Email
        href: mailto:qic108@pitt.edu

format:
  html:
    theme:
      - cosmo
      - asset/theme.scss
    mainfont: "DM Sans"
    css: styles-20260701.css
    toc: false
page-layout: full
editor: visual
